name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "test/**"
      - ".dockerignore"
      - ".eslintrc.json"
      - ".gitignore"
      - "Dockerfile"
      - "jest-e2e.json"
      - "nest-cli.json"
      - "package.json"
      - "sonar-project.properties"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - "yarn.lock"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "test/**"
      - ".dockerignore"
      - ".eslintrc.json"
      - ".gitignore"
      - "Dockerfile"
      - "jest-e2e.json"
      - "nest-cli.json"
      - "package.json"
      - "sonar-project.properties"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - "yarn.lock"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository on branch ${{ github.ref }}"
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Build
        run: |
          yarn build

  quality-gate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository on branch ${{ github.ref }}"
        uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        args: >
          -Dsonar.projectVersion=${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
